### ISSUE TITLE
Upgrade to ng 13

### ISSUE THREAD

**Issue by danielmoncada** [danielmoncada/date-time-picker#141]
Currently, the library supports applications that run on ng 13, but the library itself still contains old ng dependencies. This is to upgrade fully to ng 13. 

This includes:
- framework updates
- dependency updates
- ng 13 improvements
- see: https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296

**Comment by renemadsen** [comment]
@danielmoncada I belive I have fixed it to work with ng 13, but please do check it out, before we do a PR for the changes.

https://github.com/microting/date-time-picker/actions

I removed the references to older angular versions, since it was making my build proces spit random errors, since the upgrade to ng 13.

**Comment by danielmoncada** [comment]
@renemadsen thanks, appreciate the work. I will take a look at it this weekend

**Comment by POFerro** [comment]
Hi guys :),

I've updated my reference to version 13 of this library and it's still being built using View Engine instead of native Ivy, is this issue going to address that upgrade also?

Thanks
POFerro

**Comment by BBanoth** [comment]
> 

@danielmoncada , I am too getting the warning saying the package is built using View Engine

**Comment by vn93ksatria** [comment]
@danielmoncada  do you have the moment version?

**Comment by Rlcolli4** [comment]
I am able to run this in Angular 13 but I am still getting the warning as well @BBanoth. Any update on what is causing this or what we may need to change to prevent it from happening?

**Comment by mhamern** [comment]
@Rlcolli4 It is caused by [this line](https://github.com/danielmoncada/date-time-picker/blob/master/projects/picker/tsconfig.lib.prod.json#L4). The library is still build by the View Engine for backwards. 

You can read more [here](https://blog.angular.io/upcoming-improvements-to-angular-library-distribution-76c02f782aa4)

**Comment by krusche** [comment]
any update on this issue? when can we expect a version which is fully compatible with Angular 13? Thanks!

**Comment by danielmoncada** [comment]
@krusche I just spent the last few hours creating a new version without the MomentAdapter and closing some other small defects..

The issue here is if I don't allow View Engine, then it won't be backwards compatible anymore and that may break a lot of people's projects on older versions of Angular.

I could maintain two separate branches, but that's always a pain, cherry-picking issues to/from branches.

What type of compatibility / Ng13 functionality are you looking for? I am wondering if there are any backwards compatibility solutions I can work with.

**Comment by krusche** [comment]
I would suggest to release a new major version that only supports Angular 13 with Ivy and which completely drops View Engine. This is how other libraries handle it as well and I believe this is also what the Angular team has in mind. Supporting both will be difficult and might even become more difficult in the future.

In case of important bugfixes, you could still integrate them into older releases if there is a request from the community, but I guess more and more projects will migrate to Ivy only in the near future.

We have migrated our project https://github.com/ls1intum/Artemis to `dayjs` because `momentjs` is a legacy project in maintenance mode (see https://momentjs.com/docs/#/-project-status), so we won't mind if the `MomentAdapter` is dropped completely.

I took some time over the holidays to remove all "legacy" libraries in https://github.com/ls1intum/Artemis which are not maintained anymore to increase compatibility with Angular 13, but I would really love to keep `date-time-picker` 👍

**Comment by danielmoncada** [comment]
@krusche  yeah, I was thinking that too.. I'm assuming that's the only feasible way to handle this issue.

Also, the MomentJs adapter has already been removed and extracted in the latest version. I'll go ahead and make a DayJs one as well.

**Comment by krusche** [comment]
Just saw that we have a custom component which does the conversion: https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/shared/date-time-picker/date-time-picker.component.ts

So we would not need a DayJsAdapter

**Comment by krusche** [comment]
any updates on the Angular 13 upgrade?

**Comment by Rlcolli4** [comment]
@danielmoncada if it makes you feel better, npmjs.org does allow users to install older versions of the package if they do not want to run the newest version of Angular. 

Also any updates on the progress of this upgrade?

**Comment by Mekacher-Anis** [comment]
@danielmoncada 
any updates on this ? and thank you for doing this awesome job of maintaining the library, it's heroes like you that keep the world running !! 
let me know if you need help with the update.

**Comment by q-garethallenstringer** [comment]
If it's a blocker, I don't believe it would be a problem to release a v14 as this is what [@ngx-translate/core](https://github.com/ngx-translate/core#installation) has done

**Comment by danielmoncada** [comment]
hey everyone.. I've updated it to support full ng13. Version 14.0.0 is out on npm now.
sorry for the delay.
